apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "powerdns.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "powerdns.name" . }}
    helm.sh/chart: {{ include "powerdns.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  01-general-config.conf: |
    config-dir=/etc/pdns
    include-dir=/etc/pdns/conf.d
    guardian=yes
    loglevel=3
    setgid=pdns
    setuid=pdns
    socket-dir=/var/run
    version-string=anonymous

  00-api-key.conf: |
    api=yes
    {{ if .Values.powerdns.api_key }}
    api-key={{ .Values.powerdns.api_key }}
    {{ else }}
    api-key={{ randAlphaNum 24 }}
    {{ end }}
    webserver=yes
    # IP Address of web server to listen on
    webserver-address=0.0.0.0
    # Port of web server to listen on
    webserver-port=8081
    # Web server access is only allowed from these subnets
    webserver-allow-from=0.0.0.0/0,::/0
