apiVersion: v1
kind: Secret
metadata:
  name: {{ include "powerdns.fullname" . }}
  labels:
  {{ include "powerdns.labels" . | indent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.enabled }}
  {{- $postgrestmp := printf "%s-%s" .Release.Name "postgresql"}}
postgres_host: "{{ $postgrestmp |b64enc }}"
postgres_username: "{{ .Values.postgresql.postgresqlUsername | b64enc }}"
postgres_password: "{{ .Values.postgresql.postgresqlPassword | toString | b64enc }}"
postgres_database: "{{ .Values.postgresql.postgresqlDatabase | b64enc }}"
  {{ end }}

