{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "powerdns.serviceAccountName" . }}
  labels:
  {{ include "powerdns.labels" . | indent 4 }}
  {{- end -}}
