{{ $baseChartValues := index .Values "cray-service" }}
{{ $crayServiceValues := dict "Values" $baseChartValues "Chart" .Chart "Release" .Release}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cray-service.name" . }}-udp
  annotations:
    metallb.universe.tf/address-pool: {{ .Values.service.network }}
    metallb.universe.tf/allow-shared-ip: {{ include "cray-service.name" . }}
    cray.io/service: {{ include "cray-service.name" . }}
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app.kubernetes.io/name: {{ include "cray-service.name" $crayServiceValues }}
    app.kubernetes.io/instance: {{ include "cray-service.name" $crayServiceValues }}
spec:
  {{ if .Values.service.type }}
  type: {{ .Values.service.type }}
  {{ end }}
  {{ if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{ end }}
  {{- if (.Values.service.externalTrafficPolicy) }}
  externalTrafficPolicy: "{{ .Values.service.externalTrafficPolicy }}"
  {{- end }}
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
  selector:
    app.kubernetes.io/name: {{ include "cray-service.name" $crayServiceValues }}
    app.kubernetes.io/instance: {{ include "cray-service.name" $crayServiceValues }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cray-service.name" . }}-tcp
  annotations:
    metallb.universe.tf/address-pool: node-management
    metallb.universe.tf/allow-shared-ip: {{ include "cray-service.name" . }}
    cray.io/service: {{ include "cray-service.name" . }}
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app.kubernetes.io/name: {{ include "cray-service.name" $crayServiceValues }}
    app.kubernetes.io/instance: {{ include "cray-service.name" $crayServiceValues }}
spec:
  {{ if .Values.service.type }}
  type: {{ .Values.service.type }}
  {{ end }}
  {{ if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{ end }}
  {{- if (.Values.service.externalTrafficPolicy) }}
  externalTrafficPolicy: "{{ .Values.service.externalTrafficPolicy }}"
  {{- end }}
  ports:
  - name: dns-tcp
    port: 53
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "cray-service.name" $crayServiceValues }}
    app.kubernetes.io/instance: {{ include "cray-service.name" $crayServiceValues }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cray-service.name" . }}-api
  annotations:
    cray.io/service: {{ include "cray-service.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "cray-service.name" $crayServiceValues }}
    app.kubernetes.io/instance: {{ include "cray-service.name" $crayServiceValues }}
spec:
  type: ClusterIP
  ports:
    - port: 8081
      name: dns-api
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "cray-service.name" $crayServiceValues }}
    app.kubernetes.io/instance: {{ include "cray-service.name" $crayServiceValues }}
