{{ $baseChartValues := index .Values "cray-service" }}
{{ $crayServiceValues := dict "Values" $baseChartValues "Chart" .Chart "Release" .Release}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cray-service.name" . }}-nmn-udp
  annotations:
    metallb.universe.tf/address-pool: {{ .Values.service.nmn.network }}
    metallb.universe.tf/allow-shared-ip: {{ include "cray-service.name" . }}-nmn
    cray.io/service: {{ include "cray-service.name" . }}
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app.kubernetes.io/name: {{ include "cray-service.name" $crayServiceValues }}
    app.kubernetes.io/instance: {{ include "cray-service.name" $crayServiceValues }}
spec:
  {{ if .Values.service.nmn.type }}
  type: {{ .Values.service.nmn.type }}
  {{ end }}
  {{ if .Values.service.nmn.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.nmn.loadBalancerIP }}
  {{ end }}
  {{- if (.Values.service.nmn.externalTrafficPolicy) }}
  externalTrafficPolicy: "{{ .Values.service.nmn.externalTrafficPolicy }}"
  {{- end }}
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
  selector:
    app.kubernetes.io/name: {{ include "cray-service.name" $crayServiceValues }}
    app.kubernetes.io/instance: {{ include "cray-service.name" $crayServiceValues }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cray-service.name" . }}-nmn-tcp
  annotations:
    metallb.universe.tf/address-pool: {{ .Values.service.nmn.network }}
    metallb.universe.tf/allow-shared-ip: {{ include "cray-service.name" . }}-nmn
    cray.io/service: {{ include "cray-service.name" . }}
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app.kubernetes.io/name: {{ include "cray-service.name" $crayServiceValues }}
    app.kubernetes.io/instance: {{ include "cray-service.name" $crayServiceValues }}
spec:
  {{ if .Values.service.nmn.type }}
  type: {{ .Values.service.nmn.type }}
  {{ end }}
  {{ if .Values.service.nmn.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.nmn.loadBalancerIP }}
  {{ end }}
  {{- if (.Values.service.nmn.externalTrafficPolicy) }}
  externalTrafficPolicy: "{{ .Values.service.nmn.externalTrafficPolicy }}"
  {{- end }}
  ports:
  - name: dns-tcp
    port: 53
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "cray-service.name" $crayServiceValues }}
    app.kubernetes.io/instance: {{ include "cray-service.name" $crayServiceValues }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cray-service.name" . }}-hmn-udp
  annotations:
    metallb.universe.tf/address-pool: {{ .Values.service.hmn.network }}
    metallb.universe.tf/allow-shared-ip: {{ include "cray-service.name" . }}-hmn
    cray.io/service: {{ include "cray-service.name" . }}
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app.kubernetes.io/name: {{ include "cray-service.name" $crayServiceValues }}
    app.kubernetes.io/instance: {{ include "cray-service.name" $crayServiceValues }}
spec:
  {{ if .Values.service.hmn.type }}
  type: {{ .Values.service.hmn.type }}
  {{ end }}
  {{ if .Values.service.hmn.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.hmn.loadBalancerIP }}
  {{ end }}
  {{- if (.Values.service.hmn.externalTrafficPolicy) }}
  externalTrafficPolicy: "{{ .Values.service.hmn.externalTrafficPolicy }}"
  {{- end }}
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
  selector:
    app.kubernetes.io/name: {{ include "cray-service.name" $crayServiceValues }}
    app.kubernetes.io/instance: {{ include "cray-service.name" $crayServiceValues }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cray-service.name" . }}-hmn-tcp
  annotations:
    metallb.universe.tf/address-pool: {{ .Values.service.hmn.network }}
    metallb.universe.tf/allow-shared-ip: {{ include "cray-service.name" . }}-hmn
    cray.io/service: {{ include "cray-service.name" . }}
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app.kubernetes.io/name: {{ include "cray-service.name" $crayServiceValues }}
    app.kubernetes.io/instance: {{ include "cray-service.name" $crayServiceValues }}
spec:
  {{ if .Values.service.hmn.type }}
  type: {{ .Values.service.hmn.type }}
  {{ end }}
  {{ if .Values.service.hmn.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.hmn.loadBalancerIP }}
  {{ end }}
  {{- if (.Values.service.hmn.externalTrafficPolicy) }}
  externalTrafficPolicy: "{{ .Values.service.hmn.externalTrafficPolicy }}"
  {{- end }}
  ports:
  - name: dns-tcp
    port: 53
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "cray-service.name" $crayServiceValues }}
    app.kubernetes.io/instance: {{ include "cray-service.name" $crayServiceValues }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cray-service.name" . }}-cmn-udp
  annotations:
    metallb.universe.tf/address-pool: {{ .Values.service.cmn.network }}
    metallb.universe.tf/allow-shared-ip: {{ include "cray-service.name" . }}-cmn
    cray.io/service: {{ include "cray-service.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "cray-service.name" $crayServiceValues }}
    app.kubernetes.io/instance: {{ include "cray-service.name" $crayServiceValues }}
spec:
  {{ if .Values.service.cmn.type }}
  type: {{ .Values.service.cmn.type }}
  {{ end }}
  {{ if .Values.service.cmn.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.cmn.loadBalancerIP }}
  {{ end }}
  {{- if (.Values.service.cmn.externalTrafficPolicy) }}
  externalTrafficPolicy: "{{ .Values.service.cmn.externalTrafficPolicy }}"
  {{- end }}
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
  selector:
    app.kubernetes.io/name: {{ include "cray-service.name" $crayServiceValues }}
    app.kubernetes.io/instance: {{ include "cray-service.name" $crayServiceValues }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cray-service.name" . }}-cmn-tcp
  annotations:
    metallb.universe.tf/address-pool: {{ .Values.service.cmn.network }}
    metallb.universe.tf/allow-shared-ip: {{ include "cray-service.name" . }}-cmn
    cray.io/service: {{ include "cray-service.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "cray-service.name" $crayServiceValues }}
    app.kubernetes.io/instance: {{ include "cray-service.name" $crayServiceValues }}
spec:
  {{ if .Values.service.cmn.type }}
  type: {{ .Values.service.cmn.type }}
  {{ end }}
  {{ if .Values.service.cmn.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.cmn.loadBalancerIP }}
  {{ end }}
  {{- if (.Values.service.cmn.externalTrafficPolicy) }}
  externalTrafficPolicy: "{{ .Values.service.cmn.externalTrafficPolicy }}"
  {{- end }}
  ports:
  - name: dns-tcp
    port: 53
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "cray-service.name" $crayServiceValues }}
    app.kubernetes.io/instance: {{ include "cray-service.name" $crayServiceValues }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cray-service.name" . }}-api
  annotations:
    cray.io/service: {{ include "cray-service.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "cray-service.name" $crayServiceValues }}
    app.kubernetes.io/instance: {{ include "cray-service.name" $crayServiceValues }}
spec:
  type: ClusterIP
  ports:
    - port: 8081
      name: dns-api
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "cray-service.name" $crayServiceValues }}
    app.kubernetes.io/instance: {{ include "cray-service.name" $crayServiceValues }}
