apiVersion: v1
kind: Service
metadata:
  name: {{ include "powerdns.fullname" . }}-udp
  annotations:
    metallb.universe.tf/address-pool: node-management
    metallb.universe.tf/allow-shared-ip: {{ include "powerdns.name" . }}
    external-dns.alpha.kubernetes.io/hostname: {{ include "powerdns.name" . }}
  labels:
  {{ include "powerdns.labels" . | indent 4 }}
spec:
  type: LoadBalancer
{{ if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{ end }}
{{- if .Values.service.externalIPs }}
  externalIPs:
  {{ toYaml .Values.service.externalIPs | indent 4 }}
{{- end }}
{{- if (.Values.service.externalTrafficPolicy) }}
  externalTrafficPolicy: "{{ .Values.service.externalTrafficPolicy }}"
{{- end }}
  ports:
  - name: dns-udp
    port: 53
    protocol: UDP
  selector:
    app.kubernetes.io/name: {{ include "powerdns.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "powerdns.fullname" . }}-tcp
  annotations:
    metallb.universe.tf/address-pool: node-management
    metallb.universe.tf/allow-shared-ip: {{ include "powerdns.name" . }}
    external-dns.alpha.kubernetes.io/hostname: {{ include "powerdns.name" . }}
  labels:
  {{ include "powerdns.labels" . | indent 4 }}
spec:
  type: LoadBalancer
  {{ if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{ end }}
  {{- if .Values.service.externalIPs }}
  externalIPs:
  {{ toYaml .Values.service.externalIPs | indent 4 }}
  {{- end }}
  {{- if (.Values.service.externalTrafficPolicy) }}
  externalTrafficPolicy: "{{ .Values.service.externalTrafficPolicy }}"
  {{- end }}
  ports:
  - name: dns-tcp
    port: 53
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "powerdns.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{ if (.Values.powerdns.api_key) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "powerdns.fullname" . }}-webserver
  annotations:
    metallb.universe.tf/address-pool: node-management
    metallb.universe.tf/allow-shared-ip: {{ include "powerdns.name" . }}
    external-dns.alpha.kubernetes.io/hostname: {{ include "powerdns.name" . }}
  labels:
  {{ include "powerdns.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: dns-webserver
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "powerdns.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- end }}
