apiVersion: v2
name: cray-dns-powerdns
version: 0.2.0
description: Kubernetes resources for cray-dns-powerdns
keywords:
  - cray-dns-powerdns
  - powerdns
home: https://github.com/Cray-HPE/cray-dns-powerdns
dependencies:
  - name: cray-service
    version: ~7.0.0
    repository: https://artifactory.algol60.net/artifactory/csm-helm-charts/
maintainers:
  - name: dle-hpe
  - name: SeanWallace
  - name: spillerc-hpe
appVersion: 0.2.0
annotations:
  artifacthub.io/changes: |
    - kind: security
      description: Refactor to use patched CSM images
      links:
        - name: Github Issue
          url: https://github.com/Cray-HPE/cray-dns-powerdns/issues/10
        - name: Github PR
          url: https://github.com/Cray-HPE/cray-dns-powerdns/pull/9
  artifacthub.io/images: |
    - name: cray-dns-powerdns
      image: artifactory.algol60.net/csm-docker/stable/cray-dns-powerdns:0.2.0
    - name: docker-kubectl
      image: artifactory.algol60.net/csm-docker/stable/docker-kubectl:1.19.9
    - name: portgres
      image: artifactory.algol60.net/csm-docker/stable/postgres:13.2-alpine
  artifacthub.io/license: MIT
