apiVersion: v2
description: "Kubernetes resources for cray-dns-powerdns"
name: cray-dns-powerdns
dependencies:
  - name: cray-service
    version: "^2.6.0-0"
    repository: "@cray-internal"
home: "cloud/cray-dns-powerdns"
version: 0.0.3
