# Please refer to https://stash.us.cray.com/projects/CLOUD/repos/cray-charts/browse/stable/cray-service/values.yaml?at=refs%2Fheads%2Fmaster
# for more info on values you can set/override
# Note that cray-service.containers[*].image and cray-service.initContainers[*].image map values are one of the only structures that
# differ from the standard kubernetes container spec:
# image:
#   repository: ""
#   tag: "" (default = "latest")
#   pullPolicy: "" (default = "IfNotPresent")
cray-service:
  type: Deployment
  nameOverride: cray-dns-powerdns
  fullnameOverride: cray-dns-powerdns
  podAnnotations:
    traffic.sidecar.istio.io/excludeOutboundPorts: "53"
  containers:
    - name: "cray-dns-powerdns"
      image:
        repository: "cray/cray-dns-powerdns"
      command:
        - "sh"
        - "-c"
        - "/bin/powerdns"
      env:
        - name: AUTOCONF
          value: postgres
        - name: PGSQL_HOST
          value: cray-dns-powerdns-postgres
        - name: PGSQL_PORT
          value: "5432"
        - name: PGSQL_USER
          valueFrom:
            secretKeyRef:
              name: pdnsuser.cray-dns-powerdns-postgres.credentials
              key: username
        - name: PGSQL_PASS
          valueFrom:
            secretKeyRef:
              name: pdnsuser.cray-dns-powerdns-postgres.credentials
              key: password
        - name: PGSQL_DB
          value: "pdns"
        - name: PGSQL_DNSSEC
          value: "yes"
        - name: PDNS_API_KEY
          valueFrom:
            secretKeyRef:
              name: cray-powerdns-credentials
              key: api_key
      ports:
        - name: pdns-server-udp
          containerPort: 53
          protocol: UDP
        - name: pdns-server-tcp
          containerPort: 53
          protocol: TCP
        - name: pdns-api-tcp
          containerPort: 8081
          protocol: TCP
      livenessProbe:
        tcpSocket:
          port: 53
        initialDelaySeconds: 5
        periodSeconds: 3
      readinessProbe:
        tcpSocket:
          port: 53
        initialDelaySeconds: 5
        periodSeconds: 3
      volumeMounts:
        - name: pdns-config
          mountPath: "/etc/pdns/conf.d/00-api.conf"
          subPath: 00-api.conf
          readOnly: true
  sqlCluster:
    enabled: true
    users:
      pdnsuser: []
    databases:
      pdns: pdnsuser
    volumeSize: 10Gi
  service:
    # service definitions for this chart defined manually
    enabled: false
  volumes:
    - name: pdns-config
      configMap:
        name: cray-dns-powerdns

service:
  nmn:
    type: LoadBalancer
    loadBalancerIP:  10.92.100.85
    network: node-management
    externalTrafficPolicy:  Cluster
  hmn:
    type: LoadBalancer
    loadBalancerIP:  10.94.100.85
    network: hardware-management
    externalTrafficPolicy:  Cluster
  can:
    type: LoadBalancer
    #loadBalancerIP:  10.92.100.85
    network: customer-access-static
    externalTrafficPolicy:  Cluster