# Please refer to https://stash.us.cray.com/projects/CLOUD/repos/cray-charts/browse/stable/cray-service/values.yaml?at=refs%2Fheads%2Fmaster
# for more info on values you can set/override
# Note that cray-service.containers[*].image and cray-service.initContainers[*].image map values are one of the only structures that
# differ from the standard kubernetes container spec:
# image:
#   repository: ""
#   tag: "" (default = "latest")
#   pullPolicy: "" (default = "IfNotPresent")
cray-service:
  type: Deployment
  nameOverride: cray-dns-powerdns
  fullnameOverride: cray-dns-powerdns
  podAnnotations:
    traffic.sidecar.istio.io/excludeOutboundPorts: "5053"
  priorityClassName: csm-high-priority-service
  containers:
    cray-dns-powerdns:
      name: cray-dns-powerdns
      securityContext:
        runAsUser: 100
        runAsGroup: 101
        runAsNonRoot: true
      image:
        repository: artifactory.algol60.net/csm-docker/stable/cray-dns-powerdns
        pullPolicy: IfNotPresent
      command:
        - sh
        - -c
        - /bin/powerdns
      env:
        - name: AUTOCONF
          value: postgres
        - name: PGSQL_HOST
          value: cray-dns-powerdns-postgres
        - name: PGSQL_PORT
          value: "5432"
        - name: PGSQL_USER
          valueFrom:
            secretKeyRef:
              name: pdnsuser.cray-dns-powerdns-postgres.credentials
              key: username
        - name: PGSQL_PASS
          valueFrom:
            secretKeyRef:
              name: pdnsuser.cray-dns-powerdns-postgres.credentials
              key: password
        - name: PGSQL_DB
          value: pdns
        - name: PGSQL_DNSSEC
          value: "yes"
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: cray-powerdns-credentials
              key: pdns_api_key
      ports:
        - name: pdns-server-udp
          containerPort: 50533
          protocol: UDP
        - name: pdns-server-tcp
          containerPort: 50533
          protocol: TCP
        - name: pdns-api-tcp
          containerPort: 8081
          protocol: TCP
      livenessProbe:
        tcpSocket:
          port: 5053
        initialDelaySeconds: 5
        periodSeconds: 3
      readinessProbe:
        tcpSocket:
          port: 5053
        initialDelaySeconds: 5
        periodSeconds: 3
      volumeMounts:
        - name: pdns-config
          mountPath: /etc/pdns/pdns.conf
          subPath: pdns.conf
          readOnly: true
        - name: pdns-config
          mountPath: /etc/pdns/conf.d/00-api.conf
          subPath: 00-api.conf
          readOnly: true
        - name: pdns-config
          mountPath: /etc/pdns/conf.d/02-zone_transfer.conf
          subPath: 02-zone_transfer.conf
          readOnly: true
  sqlCluster:
    enabled: true
    users:
      pdnsuser: []
    databases:
      pdns: pdnsuser
    volumeSize: 10Gi
  service:
    # service definitions for this chart defined manually
    enabled: false
  volumes:
    - name: pdns-config
      configMap:
        name: cray-dns-powerdns
prometheusServiceMonitor:
  enabled: true
  release: cray-sysmgmt-health
  namespace: sysmgmt-health
  matchNamespace:
    - services
  interval: 59s
  scrapeTimeout: 50s
  scheme: http
  port: dns-api
service:
  nmn:
    type: LoadBalancer
    loadBalancerIP: 10.92.100.85
    network: node-management
    externalTrafficPolicy: Cluster
  hmn:
    type: LoadBalancer
    loadBalancerIP: 10.94.100.85
    network: hardware-management
    externalTrafficPolicy: Cluster
  cmn:
    type: LoadBalancer
    network: customer-management-static
    externalTrafficPolicy: Cluster
global:
  chart:
    name: cray-dns-powerdns
    version: 0.2.8
  appVersion: 0.2.8
